### ISSUE TITLE
Unable to edit/copy results

### ISSUE THREAD

**Issue by corkencor** [recite/re-cite.org#2]
not sure the clear results button is necessary
would it be better to have output as editable/able to be copied

**Comment by khanhtdk** [comment]
@corkencor actually the output of it was firstly made as "able to be selected and copied" with a mouse cursor displayed as select text caret. Current change of style displaying the cursor as block (not allowed) caret in a dimmed box which makes us feel like "unselectable".

I don't think "editable" does make sense at the result showing page.

**Comment by soodoku** [comment]
hey @khanhtdk, thanks! 

It seems we can technically select the result but it may be useful to change to a style where people don't think it is unselectable. Right now on chrome, the pointer comes up as a circle with a line through it suggesting you can't go there.

**Comment by soodoku** [comment]
The other thing is that 'clear results' button is not highlighted. So that is a small bug.
